openapi: 3.0.3
info:
  title: quick start
  description: |-
    Access library with API token
  version: 1.0.1
tags:
  - name: Account-Token
    description: Access library with Account-Token
  - name: Library-Token
    description: Access library with Library-Token
servers:
  - url: https://seafile.example.com
    description: Seafile Cloud
paths:
  /api2/ping/:
    get:
      summary: Ping server
      tags:
        - Account-Token
      description: Ping server to check if server is alive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
components:
  schemas:
    ResponseSuccess:
      type: object
      properties:
        success:
          type: boolean
